variables:
- group: nuget-deployment
- name: 'ProjectPath'
  value: 'PGO.Identity.SignedSessions'
- name: 'TestPath'
  value: 'PGO.Identity.SignedSessions.Tests'
- name: 'ReleasePath'
  value: 'PGO.Identity.SignedSessions/bin/Release'

resources:
  containers:
    - container: ci-build-dotnet
      image: mcr.microsoft.com/dotnet/core/sdk:3.1.101

jobs:
  - job: build_and_test_pack_publish_job
    pool:
      vmImage: "Ubuntu 16.04"
    container: ci-build-dotnet
    steps:
      - script: dotnet build $(ProjectPath) -c Release
      - script: dotnet test $(TestPath) -c Release --logger "trx;LogFileName=testresults.trx"4
      - script: dotnet pack $(ProjectPath) -c Release --no-build
      - script: dotnet nuget push $(ReleasePath)/*.nupkg -k $(nuget.key) -s $(nuget.url) -n true
      - task: PublishTestResults@2
        inputs:
          testRunner: VSTest
          testResultsFiles: "**/*.trx"
          failTaskOnFailedTests: true


