resources:
  containers:
    - container: ci-build-dotnet
      image: mcr.microsoft.com/dotnet/core/sdk:3.1.101

jobs:
  - job: build_and_test_pack_publish_job
    pool:
      vmImage: "Ubuntu 16.04"
    container: ci-build-dotnet
    steps:
      - script: dotnet build PGO.Identity.SignedSessions/ -c Release
      - script: dotnet test PGO.Identity.SignedSessions.Tests/ -c Release --logger "trx;LogFileName=testresults.trx"4
      - script: dotnet pack PGO.Identity.SignedSessions/ -c Release --no-build
      - task: PublishTestResults@2
        inputs:
          testRunner: VSTest
          testResultsFiles: "**/*.trx"
          failTaskOnFailedTests: true


